server:
  listen_port: 8080
  public_url: messaget.example.com
  use_auto_cert: false
  cert_path: /var/www/.cache
logging:
  file: ""
  json: false
  production: false
auth:
  password: super-secure-password
  connections_per_second: 2
  max_namespace_length: 50
