server:
  listen_port: 443
  public_url: messaget.example.com
  cert_path: /var/www/.cache
  use_auto_cert: false
  use_manual_cert: false
  manual_full_chain: ""
  manual_private: ""
logging:
  file: ""
  json: false
  production: true
auth:
  password: super-secure-password
  connections_per_second: 2
  max_namespace_length: 50
  use_client_password: false
  client_password: another-secret-password
